#+TITLE: Grad psycholinguistics

* Scheduling

  whenisgood: t748bj http://whenisgood.net/ywa7dkt/results/t748bj2
  http://whenisgood.net/ywa7dkt

* structure
  a few weeks on "foundational" stuff: speech perception, sentence processing,
  production?, pragmatics

** organizational meeting
  
** what is language and why psycholx
  
** speech perception
   categorical perception/continuous perception

   might also require introduction to the speech signal itself (for non-ling
   folks).

** spoken word recognition
   
   
** Sentence processing
   garden path sentences, ambiguity, parsing

   DLT?  classical parsing (content free) vs. lexical/constraint satisfaction
   models (MacDonald stuff?)
   
** production
   speech errors, sentence production too?

** pragmatics/discourse
   RSA vs. traditional models?  or even more basic...

** sociolx
   "three waves" of sociolx; 

** Info theory
   syntax: levy/smith and levy

   word structure (piantadosi stuff)

** noisy channel models
   how/why are these distinct from purely "bayesian"/ideal observer models?
   thinking about the production stuff and the Ryskin paper on learning the
   noise model...

** learning and adaptation
   lots of stuff here...

** speaker specific representations
   I'm thinking both the long-term memory stuff in speech and the Kamide work on
   high/low attachment preferences, maybe also informativity

** structured vs. structure free
   examplar models vs abstractionist

** variation and structure (and maybe sociolx?)
   what kind of structure is there?  (chodroff, tanner, my LCN paper)

* Preliminary schedule

** 2020-09-01 Organizational meeting
** 2020-09-08 What and why
** 2020-09-15 Speech perception
** 2020-09-22 Spoken word recognition 
** 2020-09-29 Sentence processing 
** 2020-10-06 Production 
** 2020-10-13 Pragmatics/discourse 
** 2020-10-20 Sociolx 
** 2020-10-27 Learning and adaptation 
** 2020-11-03 Talker specificity 
** 2020-11-10 Bayesian theories 
** 2020-11-17 Information theory 
** 2020-11-24 Noisy channel models 
** 2020-12-01 TBD
** 2020-12-08 (Final presentations)

* topics/theme
  I think the overall theme is going to be variability vs. structure.  How much
  do these affect processing?  How are they each represented?  What are the
  computational demands they each pose?

  Then there are the "classic" debates in psycholx: parsing wars, interactive
  activation vs. feedforward, prediction.

  The other big question is how foundational vs. "what I'm interested in now" to
  make this.  More and more I'm leaning towards foundational (it'll correct some
  of the things that are missing in Sten and Joselyn's preparation and probably
  be more useful/interesting for the others...).  But putting together a reading
  list is a little harder there I guess, so...  Maybe the first few weeks are
  going to be "basic stuff you need to know" and the last few weeks will be
  special topics?  I dunno.

  what's the point of this class?  what are these students going to get out of
  it?  they're all graduate students.  not all of them are studying language,
  but many of them are.
  
** continuous vs. discrete  
   e.g. categorical perception, graded grammaticality

** top-down vs. bottom-up processing
** exemplar models

** availability vs. info theory models (production) 

** stability vs. plasticity

** parsing wars: structure or content?
** methods
   eye tracking, corpus, psychophysics, self-paced reading, computational
   modeling

   especially interesting angle might be behavioral methods...how is language
   processing reflected in BEHAVIOR?  what are the relevant behviors and what do
   we know about them?  What kind of information can we hope to get from
   language-related behavior?  What's the time/spatial/social scale at which
   we're studying this behavior?
   
** acquisition (related to stability/plasticity?)

** what information is used when 
   modularity vs. interaction.  perspective taking.  socio stuff.  prediction
   vs. integration.

** role of context
   
** is speech/language special?
   to what extent can speech processing be explained by general auditory
   mechanisms?

* other classes
  
** BCS 501 (chigusa and mike version 2017)
   [[https://docs.google.com/spreadsheets/d/1rQjU2_a6jeoXle8hGFT93jem8XidXOs6dUcungDXz-A/edit#gid=1386834576][Schedule and readings]] [[https://docs.google.com/spreadsheets/d/1WaMJ0N-7XvIcpCCY56_dwVd-XRVJD4nhOsgHngh4nic/][(my copy)]]

   They spent first 8 classes on foundational stuff...lots of reading from the
   oxford handbook plus some supplemental stuff.  Then 6 classes on more current
   stuff I guess.

   It's a very "mike and chigusa" flavored set of topics...lots of spoken word
   recognition, information structure

   I guess I don't necessarily need to cover exactly the same material since the
   language people are all in my/karin's lab.  but I think some depth is going
   to be really important.
** BCS 501 (chigusa and mike 2015 version)
   2x weekly, much more of a survey.

** BCS 501 (Mike's lang class)
   This was pretty basic or introductory from what I remember...or rather,
   foundational.  There was a lot of reading.  No syllabus but I have the emails
   with readings/topics 

*** week 1
    Chomsky, N. (l980). Rules and representations.  The Behavioral and Brain
    Sciences, 3(1), 1-15.

    Miller, G.A. ( l965). Some preliminaries to psycholinguistics.  American
    Psychologist, 20(1), 15-20.

    Miller, G.A. (l990). The place of language in a scientific psychology. In G.A.

    Miller (Ed.), Psychological Science, 1(1), 7-14.

    Seidenberg, M. (1997) Language acquisition and use: Learning and applying
    probabilistic constraints.  Science, 275, 1599-1603.

    Hauser, M. D., Chomsky, N., &amp; Fitch, W. T. (2002). The faculty of language:
    What is it, who has it, and how did it evolve? Science, 298, 1569-1579.

*** week 2

*** week 3? dick aslin guest lecture
    probably something about speech...I have the slides 

*** (missing week)
*** sentence processing

    Frazier, L. (1987).  Sentence processing: A tutorial review.  In
    M. Coltheart (Ed.), Attention and Performance.  Hillsdale, NJ: Lawrence
    Erlbaum Associates.

    Gibson, E. (2002).  Linguistic complexity in sentence processing.  In Oxford
    Encyclopedia of Cognitive Science

    Marslen-Wilson, W.  (1973).  Linguistic structure and speech shadowing at
    very short latencies.  Nature, 244, 522-523.

    Marslen-Wilson, W.  (1975).  Sentence perception as an interactive parallel
    process.  Science, 189, 226-228.

    Levy R. (2008) Expectation-based sentence processing.  Cognition
    
    Tanenhaus, M.K. & Trueswell, J.C.  (1995). Sentence comprehension.  In:
    J.L. Miller & P.D. Eimas (Eds.). Handbook of perception and cognition
    Vol. 11: Speech, language and communication, 217-262.  San Diego, CA:
    Academic Press.

*** sentence production
    Griffin, Z. M. (2003). A reversed word length effect in coordinating the
    preparation and articulation of words in speaking. Psychonomic Bulletin and
    Review, 10(3), 603-609.

    Ferreira, V. (1996).  Is it better to give than to donate? Syntactic
    flexibility in language production.  Journal of Memory and Language, 35, 724-755
    
    Dell et al. (2008) Saying the right thing at the right time


*** perspective taking?
    Wardlow Lane et al. (2006) Don't Talk about Pink Elephants!

    Keysar et al. 2000 Taking Perspective in Conversation
*** lissa (development)

    Lenneberg, E.H.  (1969).  On explaining language: The development of
    language in children can best be understood in the context of developmental
    biology.  Science, 164, 635-643.

    Gleitman, L.R., & Newport, E.L. (1995).  The invention of language by
    children: Environmental and biological influences on the acquisition of
    language.  In L.R. Gleitman and M. Liberman (Eds.), An Invitation to
    Cognitive Science, 2nd ed.  Vol 1: Language.  Cambridge, MA: The MIT Press.

    Newport, E.L.  (2002).  Critical periods in language development.  In
    L. Nadel (Ed.), Encyclopedia of Cognitive Science.  London: Macmillan
    Publishers Ltd./Nature Publishing Group.

    Optional: Pinker, S. & Prince, A.  (1988). On language and connectionism:
    Analysis of a parallel distributed processing model of language acquisition.
    Cognition, 28, 73-193.]

    Newport, E.L., & Aslin, R.N. (2000). Innately constrained learning: Blending
    old and new approaches to language acquisition. In S. C. Howell, S. A. Fish,
    and T. Keith-Lucas (eds.), Proceedings of the 24th Annual Boston University
    Conference on Language Development.  Somerville, MA: Cascadilla Press.

    Marcus, G., Vijayan, S., Bandi Rao, S., & Vishton,
    P. M. (1999). Rule-learning in seven-month-old infants, Science, 283, 77-80.

    Aslin, R.N. & Newport, E.L. (2011).  Statistical learning: From acquiring
    specific items to forming general rules.  Current Directions in
    Psychological Science, in press.
*** visual world
*** adaptation
    (maybe this is from teh LSA institute?)
** Lang and Cog
   could do like an advanced version of this?
** my own quals
   psycholx section has some foundational stuff too...

* meetings 

** week 1 - organizational

*** Agenda
    Scheduling

    Syllabus

    Work and grading

    Final project

    Topics

*** Tuesday 12:30
    Meet next week?

** week 2 - what/why
   
*** Planning
    
**** Questions for discussion
     Does the performance/competence distinction still matter?  What role did it
     play in the historical development of psychology/cognitive science?

     How important is communication in understanding language?  Is language
     "for" communication, or something else?

     Can language /behavior/ tell us anything about linguistic /knowledge/?
     Conversely, is it possible to study language /without/ studying linguistic
     behavior?

     Why might language as Chomsky saw it be a challenge for behaviorism?

     How does the idea of innate linguistic knowledge ("universal grammar") fit
     with our current understanding?  What role does it play in current thinking
     in the field of formal/Chomskian linguistics?  What about
     psycholinguistics?

     Many of these papers make a contrast (explicitly or implicitly) between
     /statistical/ models and /grammatical/ models of linguistic knowledge.  Are
     these really in opposition?  Why or why not?

     Psychology and cognitive science have gone through a number of periods
     where different conceptions of what a good theory reigned.  What's the
     current paradigm in your area?  How is this period going to look in the
     light of history?

**** Introductory topics
     History of modern cognitive science/psychology; behaviorism and the
     cognitive revolution; the advent of connectionism

     "Scruffies and neats": "Roger Schank actually notes that he originally made
     this distinction in linguistics, related to Chomskian vs. non-Chomskian,
     but discovered it works in AI too, and other areas. " [[https://en.wikipedia.org/wiki/Neats_and_scruffies][(wiki)]]

     Marr's levels of analysis?

     Language /structure/ vs. language /content/; grammar vs. statistics

     Basics of linguistics: performance vs. competence
     
**** what's the plan
     the idea for this week is to situate psycholinguistics in the broader
     context of the field of psychology, and linguistics (and cognitive science,
     more broadly).

     So we read papers that try to give a concise overview of (some of) the
     history of cognitive science and the role of language in that (Miller), and
     some foundational issues in what we mean when we talk about language
     (communication, Hockett; grammar, HCF; statistical knowledge, Seidenberg)

     There's also this narrative that Chomsky is single-handedly responsible for
     dismantling the dominant behaviorist paradigm in his review of Skinner's
     /Verbal Behavior/; the Miller papers place that in a slightly broader
     context as well, as one part of the cognitive revolution in psychology
     which was well underway by the time Chomsky was writing that.

**** yea but what are we going to DO during class
     discuss readings ... use them as jumping off point to talk about bigger
     issues (see questions above)
